#!/usr/bin/env bash
# OpenKrab Installation Script
# Usage: curl -fsSL https://raw.githubusercontent.com/openkrab/openkrab/main/install.sh | bash
# Or:    ./install.sh

set -euo pipefail

VERSION="${OPENKRAB_VERSION:-latest}"
INSTALL_DIR="${OPENKRAB_INSTALL_DIR:-$HOME/.local/bin}"
CONFIG_DIR="${OPENKRAB_CONFIG_DIR:-$HOME/.openkrab}"
REPO="openkrab/openkrab"

detect_os() {
    case "$(uname -s)" in
        Linux*)     echo "linux" ;;
        Darwin*)    echo "macos" ;;
        CYGWIN*|MINGW*|MSYS*) echo "windows" ;;
        *)          echo "unknown" ;;
    esac
}

detect_arch() {
    case "$(uname -m)" in
        x86_64)     echo "x86_64" ;;
        aarch64|arm64) echo "arm64" ;;
        armv7)      echo "armv7" ;;
        *)          echo "x86_64" ;;
    esac
}

get_version() {
    if [[ "$VERSION" == "latest" ]]; then
        curl -sSL "https://api.github.com/repos/$REPO/releases/latest" | grep -o '"tag_name": "v[^"]*' | cut -d'"' -f4 | sed 's/v//'
    else
        echo "$VERSION"
    fi
}

download_binary() {
    local os=$1
    local arch=$2
    local ver=$3
    local fname="krabkrab-cli-$os-$arch"
    local url="https://github.com/$REPO/releases/download/v$ver/$fname.tar.gz"
    
    echo "Downloading OpenKrab v$ver for $os-$arch..."
    
    if curl -fsSL "$url" -o /tmp/krabkrab.tar.gz; then
        tar -xzf /tmp/krabkrab.tar.gz -C /tmp/
        mv "/tmp/$fname/krabkrab-cli" "$INSTALL_DIR/krabkrab" 2>/dev/null || mv "/tmp/$fname" "$INSTALL_DIR/krabkrab"
        rm -rf /tmp/krabkrab.tar.gz /tmp/$fname
        return 0
    else
        echo "Failed to download from GitHub releases, trying to build from source..."
        return 1
    fi
}

build_from_source() {
    echo "Building from source (requires Rust toolchain)..."
    
    if ! command -v cargo >/dev/null 2>&1; then
        echo "Error: Rust is not installed. Please install Rust first:"
        echo "  curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh"
        exit 1
    fi
    
    local tmpdir=$(mktemp -d)
    git clone --depth 1 "https://github.com/$REPO.git" "$tmpdir" 2>/dev/null || \
        git clone --depth 1 "file://$(pwd)" "$tmpdir"
    
    cd "$tmpdir"
    cargo build --release -p krabkrab-cli 2>/dev/null || cargo build --release 2>/dev/null || cargo build -p krabkrab-cli
    
    mkdir -p "$INSTALL_DIR"
    cp -f "./target/release/krabkrab-cli" "$INSTALL_DIR/krabkrab" 2>/dev/null || \
        cp -f "./target/debug/krabkrab-cli" "$INSTALL_DIR/krabkrab" 2>/dev/null || \
        cp -f "./target/release/krabkrab" "$INSTALL_DIR/krabkrab"
    
    cd -
    rm -rf "$tmpdir"
}

setup_config() {
    echo "Setting up configuration directory: $CONFIG_DIR"
    mkdir -p "$CONFIG_DIR"
    mkdir -p "$CONFIG_DIR/credentials"
    mkdir -p "$CONFIG_DIR/sessions"
    mkdir -p "$CONFIG_DIR/skills"
    
    if [[ ! -f "$CONFIG_DIR/openkrab.toml" ]]; then
        cat > "$CONFIG_DIR/openkrab.toml" << 'EOF'
# OpenKrab Configuration
# Generated by install.sh

[gateway]
port = 18789
bind = "loopback"

[agents.defaults]
model = "gpt-4"

[logging]
level = "info"
EOF
        echo "Created default config at $CONFIG_DIR/openkrab.toml"
    fi
}

add_to_path() {
    local shell_rc=""
    
    case "$SHELL" in
        *zsh*)   shell_rc="$HOME/.zshrc" ;;
        *bash*)  shell_rc="$HOME/.bashrc" ;;
        *fish*)  shell_rc="$HOME/.config/fish/config.fish" ;;
        *)       shell_rc="$HOME/.profile" ;;
    esac
    
    if [[ ":$PATH:" != *":$INSTALL_DIR:"* ]]; then
        echo "" >> "$shell_rc"
        echo "# OpenKrab" >> "$shell_rc"
        echo "export PATH=\"\$PATH:$INSTALL_DIR\"" >> "$shell_rc"
        echo "Added $INSTALL_DIR to PATH in $shell_rc"
        echo "Please run: source $shell_rc"
    fi
}

main() {
    local os=$(detect_os)
    local arch=$(detect_arch)
    
    echo "============================================"
    echo "  🦀 OpenKrab Installer"
    echo "============================================"
    echo ""
    echo "OS: $os"
    echo "Arch: $arch"
    echo "Install dir: $INSTALL_DIR"
    echo ""
    
    mkdir -p "$INSTALL_DIR"
    
    local ver=$(get_version)
    
    if ! download_binary "$os" "$arch" "$ver" 2>/dev/null; then
        build_from_source
    fi
    
    chmod +x "$INSTALL_DIR/krabkrab"
    
    setup_config
    add_to_path
    
    echo ""
    echo "============================================"
    echo "  ✅ Installation complete!"
    echo "============================================"
    echo ""
    echo "Run: krabkrab --help"
    echo "Or:  krabkrab onboard"
    echo ""
}

main "$@"
